import platform
import subprocess
from urllib.parse import urlencode

from django import get_version
from django.conf import settings
from django.utils import timezone

from accounts.services import application_setting_map, configured_release_branch

DEFAULT_BUG_REPORT_REPOSITORY = "aditaa/carta"
CRASH_REPORT_SESSION_KEY = "last_crash_report"


def bug_report_issue_url(report: dict[str, str], *, include_diagnostics: bool = True) -> str:
    settings_map = application_setting_map()
    repository = settings_map.get("bug_report_repository", DEFAULT_BUG_REPORT_REPOSITORY).strip()
    if not _valid_repository(repository):
        repository = DEFAULT_BUG_REPORT_REPOSITORY

    body = bug_report_issue_body(report, include_diagnostics=include_diagnostics)
    query = urlencode({"title": report.get("title", "Carta Arcanum bug report"), "body": body})
    return f"https://github.com/{repository}/issues/new?{query}"


def bug_report_issue_body(report: dict[str, str], *, include_diagnostics: bool = True) -> str:
    sections = [
        "## What happened",
        report.get("what_happened", "").strip() or "_No details provided._",
        "",
        "## What I expected",
        report.get("expected", "").strip() or "_No details provided._",
        "",
        "## Steps to reproduce",
        report.get("steps", "").strip() or "_No steps provided._",
    ]
    crash_context = report.get("crash_context")
    if include_diagnostics and isinstance(crash_context, dict):
        sections.extend(["", "## Detected crash", _crash_context_markdown(crash_context)])
    if include_diagnostics:
        sections.extend(["", "## Anonymous diagnostics", _diagnostics_markdown()])
    sections.extend(
        [
            "",
            "## Privacy note",
            (
                "This report was generated by Carta Arcanum. Review it before submitting "
                "and remove anything you do not want to share."
            ),
        ]
    )
    return "\n".join(sections)


def bug_report_diagnostics() -> dict[str, str]:
    release_branch = configured_release_branch()
    return {
        "Release channel": "testing" if release_branch == "main" else "stable",
        "Configured release branch": release_branch,
        "Git branch": _git_value(["rev-parse", "--abbrev-ref", "HEAD"]),
        "Git commit": _git_value(["rev-parse", "--short", "HEAD"]),
        "Python": platform.python_version(),
        "Django": get_version(),
        "Database engine": settings.DATABASES["default"]["ENGINE"],
        "Debug mode": str(bool(settings.DEBUG)).lower(),
        "Rules file": settings.CURRENT_RULES_FILE.name,
    }


def record_crash_for_bug_report(request, exc: Exception, *, query_count: int) -> None:
    session = getattr(request, "session", None)
    if session is None:
        return
    resolver_match = getattr(request, "resolver_match", None)
    route_name = getattr(resolver_match, "view_name", "") or "unknown"
    session[CRASH_REPORT_SESSION_KEY] = {
        "when": timezone.now().isoformat(),
        "exception_type": exc.__class__.__name__,
        "route": route_name,
        "method": getattr(request, "method", ""),
        "query_count": str(query_count),
    }
    if hasattr(session, "modified"):
        session.modified = True


def crash_report_initial(crash_context: dict[str, str] | None) -> dict[str, str | bool]:
    if not crash_context:
        return {"title": "Bug report", "include_diagnostics": True}
    route = crash_context.get("route", "unknown")
    exception_type = crash_context.get("exception_type", "ServerError")
    return {
        "title": f"Crash report: {route}",
        "what_happened": (
            f"Carta Arcanum detected an unhandled {exception_type} on route `{route}`."
        ),
        "steps": "Please describe what you were doing before the crash.",
        "include_diagnostics": True,
    }


def _crash_context_markdown(crash_context: dict[str, str]) -> str:
    safe_keys = ("when", "exception_type", "route", "method", "query_count")
    lines = ["```text"]
    for key in safe_keys:
        if key in crash_context:
            lines.append(f"{key}: {crash_context[key]}")
    lines.append("```")
    return "\n".join(lines)


def _diagnostics_markdown() -> str:
    lines = ["```text"]
    lines.extend(f"{key}: {value}" for key, value in bug_report_diagnostics().items())
    lines.append("```")
    return "\n".join(lines)


def _git_value(command: list[str]) -> str:
    completed = subprocess.run(
        ["git", *command],
        cwd=settings.BASE_DIR,
        text=True,
        capture_output=True,
        check=False,
        timeout=5,
    )
    if completed.returncode != 0:
        return "unknown"
    return completed.stdout.strip() or "unknown"


def _valid_repository(repository: str) -> bool:
    if repository.count("/") != 1:
        return False
    owner, name = repository.split("/", 1)
    return bool(owner and name and " " not in repository)
