import platform
import subprocess
from urllib.parse import urlencode

from django import get_version
from django.conf import settings

from accounts.services import application_setting_map, configured_release_branch

DEFAULT_BUG_REPORT_REPOSITORY = "aditaa/carta"


def bug_report_issue_url(report: dict[str, str], *, include_diagnostics: bool = True) -> str:
    settings_map = application_setting_map()
    repository = settings_map.get("bug_report_repository", DEFAULT_BUG_REPORT_REPOSITORY).strip()
    if not _valid_repository(repository):
        repository = DEFAULT_BUG_REPORT_REPOSITORY

    body = bug_report_issue_body(report, include_diagnostics=include_diagnostics)
    query = urlencode({"title": report.get("title", "Carta Arcanum bug report"), "body": body})
    return f"https://github.com/{repository}/issues/new?{query}"


def bug_report_issue_body(report: dict[str, str], *, include_diagnostics: bool = True) -> str:
    sections = [
        "## What happened",
        report.get("what_happened", "").strip() or "_No details provided._",
        "",
        "## What I expected",
        report.get("expected", "").strip() or "_No details provided._",
        "",
        "## Steps to reproduce",
        report.get("steps", "").strip() or "_No steps provided._",
    ]
    if include_diagnostics:
        sections.extend(["", "## Anonymous diagnostics", _diagnostics_markdown()])
    sections.extend(
        [
            "",
            "## Privacy note",
            (
                "This report was generated by Carta Arcanum. Review it before submitting "
                "and remove anything you do not want to share."
            ),
        ]
    )
    return "\n".join(sections)


def bug_report_diagnostics() -> dict[str, str]:
    release_branch = configured_release_branch()
    return {
        "Release channel": "testing" if release_branch == "main" else "stable",
        "Configured release branch": release_branch,
        "Git branch": _git_value(["rev-parse", "--abbrev-ref", "HEAD"]),
        "Git commit": _git_value(["rev-parse", "--short", "HEAD"]),
        "Python": platform.python_version(),
        "Django": get_version(),
        "Database engine": settings.DATABASES["default"]["ENGINE"],
        "Debug mode": str(bool(settings.DEBUG)).lower(),
        "Rules file": settings.CURRENT_RULES_FILE.name,
    }


def _diagnostics_markdown() -> str:
    lines = ["```text"]
    lines.extend(f"{key}: {value}" for key, value in bug_report_diagnostics().items())
    lines.append("```")
    return "\n".join(lines)


def _git_value(command: list[str]) -> str:
    completed = subprocess.run(
        ["git", *command],
        cwd=settings.BASE_DIR,
        text=True,
        capture_output=True,
        check=False,
        timeout=5,
    )
    if completed.returncode != 0:
        return "unknown"
    return completed.stdout.strip() or "unknown"


def _valid_repository(repository: str) -> bool:
    if repository.count("/") != 1:
        return False
    owner, name = repository.split("/", 1)
    return bool(owner and name and " " not in repository)
