# Generated by Django 5.2.14 on 2026-05-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("buildings", "0001_initial"),
        ("rulesets", "0002_itemreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductionRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=160)),
                ("recipe_type", models.CharField(max_length=120)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="production_recipes",
                        to="buildings.buildingdefinition",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipes",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ruleset", "key"), name="unique_production_recipe_ruleset_key"
                    )
                ],
            },
        ),
    ]
