# Generated by Django 5.2.14 on 2026-05-13 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_membershipinvitation'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ownership', '0003_house_own_house_kingdom_idx_house_own_house_name_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='applicationsetting',
            index=models.Index(fields=['label', 'key'], name='acct_setting_label_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['-created_at', '-id'], name='acct_audit_created_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['action', '-created_at'], name='acct_audit_action_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['actor', '-created_at'], name='acct_audit_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlogentry',
            index=models.Index(fields=['target_type', 'target_id'], name='acct_audit_target_idx'),
        ),
        migrations.AddIndex(
            model_name='denizenprofile',
            index=models.Index(fields=['status'], name='acct_profile_status_idx'),
        ),
        migrations.AddIndex(
            model_name='denizenprofile',
            index=models.Index(fields=['system_account'], name='acct_profile_system_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['invitee', 'status', '-created_at'], name='acct_inv_invitee_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['house', 'status'], name='acct_inv_house_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['kingdom', 'status'], name='acct_inv_kingdom_idx'),
        ),
        migrations.AddIndex(
            model_name='membershipinvitation',
            index=models.Index(fields=['status', '-created_at'], name='acct_inv_status_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active', 'is_staff'], name='acct_user_active_staff_idx'),
        ),
    ]
