# Generated by Django 5.2.14 on 2026-05-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ruleset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("game", models.CharField(max_length=160)),
                ("rules_version", models.CharField(max_length=80)),
                ("schema_version", models.CharField(max_length=80)),
                ("source_path", models.CharField(max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("raw_data", models.JSONField(default=dict)),
                ("imported_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["game", "rules_version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("game", "rules_version"), name="unique_ruleset_game_version"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="RulesetImportLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("source_path", models.CharField(max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")], max_length=24
                    ),
                ),
                ("message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ruleset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="import_logs",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
