# Generated by Django 5.2.14 on 2026-05-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulesets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemReference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("settlement_upgrade_cost", "Settlement upgrade cost"),
                            ("settlement_upkeep", "Settlement upkeep"),
                            ("build_cost", "Build cost"),
                            ("building_upkeep", "Building upkeep"),
                            ("recipe_input", "Recipe input"),
                            ("recipe_output", "Recipe output"),
                        ],
                        max_length=80,
                    ),
                ),
                ("owner_type", models.CharField(max_length=80)),
                ("owner_key", models.CharField(max_length=160)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("resource", "Resource"),
                            ("currency", "Currency"),
                            ("unit", "Unit"),
                            ("special", "Special"),
                        ],
                        max_length=24,
                    ),
                ),
                ("item_key", models.CharField(max_length=160)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_refs",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "owner_type", "owner_key", "purpose", "sort_order", "id"],
                "indexes": [
                    models.Index(
                        fields=["ruleset", "owner_type", "owner_key", "purpose"],
                        name="rulesets_it_ruleset_bee47c_idx",
                    ),
                    models.Index(
                        fields=["ruleset", "item_type", "item_key"],
                        name="rulesets_it_ruleset_165463_idx",
                    ),
                ],
            },
        ),
    ]
