# Generated by Django 5.2.14 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rulesets", "0002_itemreference"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemreference",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("settlement_upgrade_cost", "Settlement upgrade cost"),
                    ("settlement_upkeep", "Settlement upkeep"),
                    ("build_cost", "Build cost"),
                    ("building_upkeep", "Building upkeep"),
                    ("recipe_input", "Recipe input"),
                    ("recipe_output", "Recipe output"),
                    ("transport_build_cost", "Transport build cost"),
                    ("transport_repair_cost", "Transport repair cost"),
                    ("transport_upkeep", "Transport upkeep"),
                ],
                max_length=80,
            ),
        ),
    ]
