# Generated by Django 5.2.14 on 2026-05-14 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rulesets", "0003_alter_itemreference_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="PhaseDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="phases",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="PhaseUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("unlock_type", models.CharField(blank=True, max_length=120)),
                ("description", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "phase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocks",
                        to="progression.phasedefinition",
                    ),
                ),
            ],
            options={
                "ordering": ["phase", "sort_order", "key"],
            },
        ),
        migrations.CreateModel(
            name="TitleDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(blank=True, max_length=120)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("effects", models.JSONField(blank=True, default=list)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="titles",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "category", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="phasedefinition",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_phase_definition_ruleset_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="phaseunlock",
            constraint=models.UniqueConstraint(
                fields=("phase", "key"), name="unique_phase_unlock_phase_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="titledefinition",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_title_definition_ruleset_key"
            ),
        ),
    ]
