# Generated by Django 5.2.14 on 2026-05-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rulesets", "0003_alter_itemreference_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnershipRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("entity_type", models.CharField(max_length=120)),
                ("allowed", models.JSONField(blank=True, default=list)),
                ("not_allowed", models.JSONField(blank=True, default=list)),
                ("notes", models.JSONField(blank=True, default=list)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ownership_rules",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "entity_type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ruleset", "entity_type"),
                        name="unique_ownership_rule_ruleset_entity_type",
                    )
                ],
            },
        ),
    ]
