# Generated by Django 5.2.14 on 2026-05-07 21:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("ownership", "0002_kingdom_house_housemembership_kingdommembership"),
        ("rulesets", "0003_alter_itemreference_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HoldingAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("denizen", "Denizen"),
                            ("house", "House"),
                            ("kingdom", "Kingdom"),
                            ("three_crowns_denizen", "Three Crowns denizen"),
                            ("three_crowns_house", "Three Crowns house"),
                            ("three_crowns_kingdom", "Three Crowns kingdom"),
                        ],
                        max_length=40,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=160)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding_accounts",
                        to="ownership.house",
                    ),
                ),
                (
                    "kingdom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding_accounts",
                        to="ownership.kingdom",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holding_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["scope", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="HoldingBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("resource", "Resource"),
                            ("currency", "Currency"),
                            ("unit", "Unit"),
                            ("special", "Special"),
                        ],
                        max_length=24,
                    ),
                ),
                ("item_key", models.CharField(max_length=160)),
                ("quantity", models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balances",
                        to="holdings.holdingaccount",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holding_balances",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["account", "item_type", "item_key"],
            },
        ),
        migrations.CreateModel(
            name="HoldingLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("deposit", "Deposit"),
                            ("withdrawal", "Withdrawal"),
                            ("transfer", "Transfer"),
                            ("correction", "Correction"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("resource", "Resource"),
                            ("currency", "Currency"),
                            ("unit", "Unit"),
                            ("special", "Special"),
                        ],
                        max_length=24,
                    ),
                ),
                ("item_key", models.CharField(max_length=160)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="holdings.holdingaccount",
                    ),
                ),
                (
                    "related_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_ledger_entries",
                        to="holdings.holdingaccount",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="holding_ledger",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="holdingaccount",
            constraint=models.UniqueConstraint(
                fields=("scope", "user"), name="unique_holding_account_scope_user"
            ),
        ),
        migrations.AddConstraint(
            model_name="holdingaccount",
            constraint=models.UniqueConstraint(
                fields=("scope", "house"), name="unique_holding_account_scope_house"
            ),
        ),
        migrations.AddConstraint(
            model_name="holdingaccount",
            constraint=models.UniqueConstraint(
                fields=("scope", "kingdom"), name="unique_holding_account_scope_kingdom"
            ),
        ),
        migrations.AddConstraint(
            model_name="holdingbalance",
            constraint=models.UniqueConstraint(
                fields=("account", "ruleset", "item_type", "item_key"),
                name="unique_holding_balance_account_ruleset_item",
            ),
        ),
    ]
