# Generated by Django 5.2.14 on 2026-05-07 21:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("holdings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="holdingaccount",
            name="scope",
            field=models.CharField(
                choices=[
                    ("denizen", "Denizen"),
                    ("house", "House"),
                    ("house_denizen", "House-held denizen"),
                    ("kingdom", "Kingdom"),
                    ("three_crowns_denizen", "Three Crowns denizen"),
                    ("three_crowns_house", "Three Crowns house"),
                    ("three_crowns_kingdom", "Three Crowns kingdom"),
                ],
                max_length=40,
            ),
        ),
    ]
