# Generated by Django 5.2.14 on 2026-05-07 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rulesets", "0003_alter_itemreference_purpose"),
    ]

    operations = [
        migrations.CreateModel(
            name="TransportDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("transport_type", models.CharField(max_length=120)),
                ("home_requirement", models.TextField(blank=True)),
                ("health", models.PositiveIntegerField()),
                ("storage", models.PositiveIntegerField()),
                ("quarters", models.PositiveIntegerField()),
                ("actions", models.JSONField(blank=True, default=list)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transports",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ruleset", "key"), name="unique_transport_definition_ruleset_key"
                    )
                ],
            },
        ),
    ]
