# Generated by Django 5.2.14 on 2026-05-07 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rulesets", "0002_itemreference"),
    ]

    operations = [
        migrations.CreateModel(
            name="SettlementTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("min_buildings", models.PositiveIntegerField()),
                ("max_buildings", models.PositiveIntegerField()),
                ("prerequisites", models.JSONField(blank=True, default=list)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settlement_tiers",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "min_buildings", "key"],
            },
        ),
        migrations.CreateModel(
            name="BuildingDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(max_length=120)),
                ("map_visible", models.BooleanField(default=False)),
                ("requirements", models.JSONField(blank=True, default=list)),
                ("effects", models.JSONField(blank=True, default=list)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buildings",
                        to="rulesets.ruleset",
                    ),
                ),
                (
                    "settlement_requirement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="required_by_buildings",
                        to="buildings.settlementtier",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="settlementtier",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_settlement_tier_ruleset_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="buildingdefinition",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_building_definition_ruleset_key"
            ),
        ),
    ]
