# Generated by Django 5.2.14 on 2026-05-08 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("buildings", "0001_initial"),
        ("ownership", "0002_kingdom_house_housemembership_kingdommembership"),
        ("rulesets", "0003_alter_itemreference_purpose"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OwnedBuilding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "owner_scope",
                    models.CharField(
                        choices=[
                            ("denizen", "Denizen"),
                            ("house", "House"),
                            ("kingdom", "Kingdom"),
                        ],
                        max_length=24,
                    ),
                ),
                ("nickname", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("damaged", "Damaged"),
                        ],
                        default="active",
                        max_length=24,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "definition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_buildings",
                        to="buildings.buildingdefinition",
                    ),
                ),
                (
                    "house",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_buildings",
                        to="ownership.house",
                    ),
                ),
                (
                    "kingdom",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_buildings",
                        to="ownership.kingdom",
                    ),
                ),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="owned_buildings",
                        to="rulesets.ruleset",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_buildings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["definition__name", "nickname", "id"],
                "indexes": [
                    models.Index(
                        fields=["owner_scope", "status"], name="buildings_o_owner_s_204d81_idx"
                    ),
                    models.Index(
                        fields=["ruleset", "definition"], name="buildings_o_ruleset_3abb79_idx"
                    ),
                ],
            },
        ),
    ]
