# Generated by Django 5.2.14 on 2026-05-15 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign_map', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaignmapversion',
            options={'ordering': ['map_type', 'name', '-imported_at', '-id']},
        ),
        migrations.AddField(
            model_name='campaignmapversion',
            name='map_type',
            field=models.CharField(choices=[('world', 'World'), ('detail', 'Detail')], default='world', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignmapversion',
            name='parent_key',
            field=models.SlugField(blank=True, max_length=120),
        ),
    ]
