# Generated by Django 5.2.14 on 2026-05-07 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("rulesets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_categories",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "key"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="rulesets.ruleset",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="resources",
                        to="resources.resourcecategory",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "key"],
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("category", models.CharField(max_length=120)),
                ("attack", models.IntegerField(blank=True, null=True)),
                ("defense", models.IntegerField(blank=True, null=True)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "key"],
            },
        ),
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("key", models.CharField(max_length=120)),
                ("name", models.CharField(max_length=160)),
                ("copper_value", models.IntegerField(blank=True, null=True)),
                (
                    "ruleset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currencies",
                        to="rulesets.ruleset",
                    ),
                ),
            ],
            options={
                "ordering": ["ruleset", "copper_value", "key"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("ruleset", "key"), name="unique_currency_ruleset_key"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="resourcecategory",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_resource_category_ruleset_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="resource",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_resource_ruleset_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("ruleset", "key"), name="unique_unit_ruleset_key"
            ),
        ),
    ]
