from __future__ import annotations

import json
import os
from dataclasses import dataclass
from pathlib import Path

import pymysql
from django.conf import settings
from django.contrib.auth import get_user_model
from django.db import DatabaseError, ProgrammingError


@dataclass(frozen=True)
class DatabaseConfig:
    host: str
    port: int
    database: str
    test_database: str
    user: str
    password: str


def current_database_config() -> DatabaseConfig:
    database = settings.DATABASES["default"]
    return DatabaseConfig(
        host=database["HOST"],
        port=int(database["PORT"]),
        database=database["NAME"],
        test_database=database["TEST"]["NAME"],
        user=database["USER"],
        password=database["PASSWORD"],
    )


def test_mysql_connection(config: DatabaseConfig) -> None:
    connection = pymysql.connect(
        host=config.host,
        port=config.port,
        user=config.user,
        password=config.password,
        database=config.database,
        connect_timeout=3,
        charset="utf8mb4",
    )
    connection.close()


def write_database_env(config: DatabaseConfig, path: Path | None = None) -> Path:
    path = path or settings.INSTALLER_ENV_FILE
    path.parent.mkdir(parents=True, exist_ok=True)
    content = "\n".join(
        [
            "# Local Carta Arcanum installer configuration.",
            "# This file is generated by the web installer and should not be committed.",
            _env_line("MYSQL_HOST", config.host),
            _env_line("MYSQL_PORT", str(config.port)),
            _env_line("MYSQL_DATABASE", config.database),
            _env_line("MYSQL_TEST_DATABASE", config.test_database),
            _env_line("MYSQL_USER", config.user),
            _env_line("MYSQL_PASSWORD", config.password),
            "",
        ]
    )
    temporary_path = path.with_suffix(f"{path.suffix}.tmp")
    temporary_path.write_text(content, encoding="utf-8")
    os.replace(temporary_path, path)
    return path


def installer_is_locked() -> bool:
    try:
        return get_user_model().objects.exists()
    except (DatabaseError, ProgrammingError):
        return False


def _env_line(key: str, value: str) -> str:
    return f"{key}={json.dumps(value)}"
